    
    #include "mapping.inc"
    ;#include "stm8s105k4.inc"
    #include "GlobalVar.inc"
    #include "MacroFunction.inc"
    #include "Common.inc"
    ;#include "LCD.inc"
    #include "ADC.inc"
    ;#include "Key.inc"
    ;#include "Timer.inc"
    ;#include "Initialize.inc"
    
    ;EXTERN LCD_Init.W
    ;EXTERN GPIO_Init.W
    EXTERN Main_Init.W
    ;EXTERN DispADC.W
    EXTERN StartUp_Init.W
    
    
    